config/routes.rb
Rails.application.routes.draw do

  root "preinternship#home"
  get "preinternship/about"

  devise_for :users, controllers: { registrations: "users/registrations" }
  resource :contacts, only: %i[new create]
  resources :articles, only: %i[index show]

  resource :user, only: [] do
    resources :articles, only: %i[index show edit update destroy new create], module: :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend Enumerize

  paginates_per 5

  AVALIABLE_STATUSES = ["public", "draft", "archive"].freeze

  belongs_to :user

  validates :title, :content, presence: true, length: { minimum: 3 }
  validates :status, presence: true

  enumerize :status, in: AVALIABLE_STATUSES , scope: :shallow, default: :draft
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :articles, dependent: :destroy

  validates :firstname, :lastname, presence: true
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  include Authentication
  include Authorization
end

app/controllers/articles/statuses_controller.rb
module Articles
  class StatusesController < ApplicationController
    expose :article, parent: :current_user

    before_action :authenticate_user!

    def update
      authorize article
      article.update(status_params)
    end

    private

    def article_params
      params.require(:article).permit(:status)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  expose :decorated_articles, -> { ArticleDecorator.decorate_collection(fetch_articles) }
  expose :article, scope: -> { Article.public }

  def index
  end

  def show
  end

  private

  def fetch_articles
    Article.public.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper do
      def current_user
        super.decorate if user_signed_in?
      end
    end
  end

  private

  def devise_parameter_sanitizer
    if resource_class == User
      ::UserParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end

  private

  def user_not_authorized
    flash[:notice] = I18n.t("errors.messages.not_authorized_for_action")
    redirect_to(root_path)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :contact_params, only: %i(create)

  def new
    @contact = ContactMailer.new
  end

  def create
    @contact = ContactMailer.new(contact_params)
    if @contact.deliver
      flash.notice = "Thank you for your message. I'll get back to you soon!"
      redirect_to root_path
    else
      flash.notice = "Message did not send."
      render :new
    end
  end

  private
  def contact_params
    params.require(:contact_mailer).permit(:name, :email, :message)
  end
end

app/controllers/preinternship_controller.rb
class PreinternshipController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users/articles_controller.rb
module Users
  class ArticlesController < ApplicationController
    expose :decorated_articles, -> { ArticleDecorator.decorate_collection(fetch_articles) }
    expose :article, parent: :current_user

    before_action :authenticate_user!
    before_action :authorize_resource!, only: %i[edit update destroy]

    def index
    end

    def show
    end

    def create
      create_article
      respond_with article, location: -> { user_article_path(article.id) }
    end

    def new
    end

    def edit
    end

    def update
      update_article
      respond_with article, location: user_article_path(article.id)
    end

    def destroy
      article.destroy
      respond_with article, location: user_articles_path
    end

  private

    def create_article
      Articles::Create.call(article: article, article_params: article_params)
    end

    def update_article
      Articles::Update.call(article: article, article_params: article_params)
    end

    def fetch_articles
      filtered_articles.order(created_at: :desc).page(params[:page])
    end

    def filtered_articles
      FilteredArticlesQuery.new(raw_relation, filter_params).all
    end

    def raw_relation
      current_user.articles
    end

    def filter_params
      params.permit(:status).with_defaults(status: "public").to_h
    end

    def authorize_resource!
      authorize article, :manage?
    end

    def article_params
      params.require(:article).permit(:title, :content, :status)
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    protected

    def account_update_params
      params = devise_parameter_sanitizer.sanitize(:account_update)

      if passwords_blank?(params)
        params.except(:password, :password_confirmation)
      else
        params
      end
    end

    def passwords_blank?(params)
      params[:password].blank? && params[:password_confirmation].blank?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/preinternship_helper.rb
module PreinternshipHelper
end

app/views/articles/index.html.slim
h1 Articles
ul
  - decorated_articles.each do |article|
   li
      = link_to article.article_link, article
footer class="footer"
  div align="center"
    = paginate decorated_articles

app/views/articles/show.html.slim
h1 = article.title
p = article.content
- if policy(article).manage?
 =< link_to "Edit", edit_user_article_path(article), class: "btn btn-secondary"
 =< link_to "Destroy", user_article_path(article), class: "btn btn-danger", method: :delete
 - if article.status.public?
  = form_with model: [:user, article] do |form|
    = form.hidden_field :status, value: "draft"
    = form.submit "Make a draft"
 - if article.status.draft?
  = form_with model: [:user, article] do |form|
    = form.hidden_field :status, value: "public"
    = form.submit "Publish"
  div = link_to "Back to drafted articles", articles_path(status: :draft), class: "btn btn-outline-secondary"
= link_to "Back to articles", articles_path, class: "btn btn-primary"

app/views/contacts/_contact_form.html.slim
= form_for @contact, url: contacts_path do |f|
  .col-md-6
    = f.label :name
    br
    = f.text_field :name, class: "contact-form-text-area"
    - @contact.errors.full_messages_for(:name).each do |message|
      div = message
    br
    = f.label :email
    br
    = f.text_field :email, class: "contact-form-text-area"
    - @contact.errors.full_messages_for(:email).each do |message|
      div = message
    br
    = f.label :message
    br
    = f.text_area :message, rows: 8, cols: 40, class: "contact-form-text-area", placeholder: "Send me a message"
    - @contact.errors.full_messages_for(:message).each do |message|
      div = message
    br
    = f.submit "Send Message", class: "btn btn-primary"
    =< link_to "Back", root_path, class: "btn btn-secondary"

app/views/contacts/new.html.slim
h2 = "Please fill in all the fields to mail your message"
= render "contact_form"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Preinternship
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css", media: "all", "data-turbolinks-track": "reload"
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
  body
  header.p-3.bg-dark.text-white
    .container
      nav.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
        ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
          li = link_to "Blog", root_path, class: "nav-link px-2 text-white"
          li = link_to "About me", preinternship_about_path, class: "nav-link px-2 text-white"
          li = link_to "All Articles", articles_path, class: "nav-link px-2 text-white"
          - if user_signed_in?
            li = link_to "My Articles", user_articles_path, class: "nav-link px-2 text-white"
            li = link_to "Sign out", destroy_user_session_path,
                                    method: :delete, class: "nav-link px-2 text-white",
                                    data: { confirm: "Are you sure?" }
            li = current_user.fullname
          - else
            li = link_to "Sign in", new_user_session_path, class: "nav-link px-2 text-white"
            li = link_to "Sign up", new_user_registration_path, class: "nav-link px-2 text-white"
        a =< link_to "Contact me", new_contacts_path, class: "nav-link px-2 text-white"
p.notice
= notice
p.alert
= alert
= yield

app/views/preinternship/about.html.slim
h1
  | Preinternship#about
p
  | Find me in app/views/preinternship/about.html.erb
= link_to "Back", :back

app/views/preinternship/home.html.slim
h1
  | Blog
- if user_signed_in?
  span
    | Hello,
    =< current_user.fullname_with_email
  div
    = link_to "Edit profile", edit_user_registration_path
- else
  | Hello,
   click sign in for log in or sign up if you not registred

app/views/users/articles/_form.html.slim
= form_with model: [:user, article] do |form|
  div
    = form.label :title
    br/
    = form.text_field :title
    - article.errors.full_messages_for(:title).each do |message|
      div = message

  div
    = form.label :content
    br/
    = form.text_area :content
    - article.errors.full_messages_for(:content).each do |message|
      div = message
  div
    = form.submit
= link_to "Back to articles", user_articles_path, class: "btn btn-primary"

app/views/users/articles/edit.html.slim
h1 Edit article
= render "form", article: article

app/views/users/articles/index.html.slim
h1 Articles
ul
  - decorated_articles.each do |article|
    li
      =  link_to article.article_link, user_article_path(article)

  = link_to "New Article", new_user_article_path, class: "btn btn-success"
  - if params[:status] != "draft"
    =< link_to "Drafted articles", user_articles_path(status: :draft), class: "btn btn-outline-secondary"
  - if current_page?(user_articles_path(status: :draft))
    = link_to "Back to articles", user_articles_path, class: "btn btn-primary"
footer class="footer"
  div align="center"
    = paginate decorated_articles

app/views/users/articles/new.html.slim
h1 New Article
= render "form", article: article

app/views/users/articles/show.html.slim
h1 = article.title
p = article.content
- if policy(article).manage?
 p =< link_to "Edit", edit_user_article_path(article), class: "btn btn-secondary"
 p =< link_to "Destroy", user_article_path(article), class: "btn btn-danger", method: :delete
 - if article.status.public?
  p = form_with model: [:user, article] do |form|
      = form.hidden_field :status, value: "draft"
      = form.submit "Make a draft", class: "btn btn-warning"
  p =< link_to "Drafted articles", user_articles_path(status: :draft), class: "btn btn-outline-secondary"
 - if article.status.draft?
  p = form_with model: [:user, article] do |form|
      = form.hidden_field :status, value: "public"
      = form.submit "Publish", class: "btn btn-success"
  p = link_to "Back to drafted articles", user_articles_path(status: :draft), class: "btn btn-outline-secondary"
= link_to "Back to articles", user_articles_path, class: "btn btn-primary"

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
                        count: resource.errors.count,
                        resource: resource.class.model_name.human.downcase)
  ul
    - resource.errors.full_messages.each do |message|
      li
        = message

app/views/users/shared/_links.html.slim
- if controller_name != "sessions"
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != "registrations"
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != "passwords" && controller_name != "registrations"
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != "confirmations"
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks"
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post
    br